[meta]
version = 1
updated = "2026-02-14"

[packages.stato-self]
description = "Stato development expertise: compiler design, composition algebra, testing strategy, cross-platform bridges"
author = "Min Dai"
url = "https://github.com/genecell/stato/raw/master/docs/registry/packages/stato-self.stato"
version = "0.5.0"
tags = ["python", "cli", "packaging", "compiler", "testing", "composition"]
modules = 8
updated = "2026-02-14"



[packages.piaso-scrna-expert]
description = "scRNA-seq analysis pipeline using PIASO + Scanpy + COSG"
author = "Min Dai"
version = "0.0.1"
url = "https://raw.githubusercontent.com/genecell/stato/main/docs/registry/packages/piaso-scrna-skills-testing.stato"
tags = ["bioinformatics", "single-cell", "scRNA-seq", "piaso", "scanpy", "COSG", "scRNAseq"]
